### ISSUE TITLE
add word prediction

### ISSUE THREAD

**Issue by willwade** [AceCentre/MorseWriter#15]
This would be awesome - somehow provide word prediction. Each word in the prediction is selectable by a morse combination (e.g. like a F key )

**Comment by willwade** [comment]
maybe using https://presage.sourceforge.io/applications/

**Comment by willwade** [comment]
I'm imagining a row - with words..

what (..--..-) who (..---..-) why (..--..-) 

which would dynamically change as letters typed. Ideally supports next word prediction to

**Comment by hosseinamin** [comment]
Presage is a great program. This is what we need. It's good for pasco too.
